### ISSUE TITLE
`function has no attribute 'reset'` error when running 02-pytorch-asr LabSolution

### ISSUE THREAD

**Issue by NickleDave** [jeremyfix/deepcs#2]
Hi @jeremyfix 

I am working with the solution you have provided your students in this lab:
https://github.com/jeremyfix/deeplearning-lectures/blob/master/LabsSolutions/02-pytorch-asr/main_ctc.py

Thanks so much for sharing these lectures and this package publicly.  
Surprisingly it's one of the few examples I can find of using the `pack_sequence` functions in `torch` with a CNN-LSTM model for speech tasks (most examples use tokenized embedded text for NLP).

I hit an error in `deepcs` when running the script.  
I understand you develop this package for your classes, and not for general use, so I am just telling you in case it helps you avoid issues teaching -- I'm not asking for a fix or anything.

When I run I get the following error.
```
    bm.reset()
AttributeError: 'function' object has no attribute 'reset'
```
I'll paste the full traceback below.

It's caused by this code block:
https://github.com/jeremyfix/deepcs/blob/ad69e4c50ab2c0404bc6a8ca54b87780c91dd570/deepcs/training.py#L59
```
    for bname, bm in batch_metrics.items():
        bm.reset()
```

I think this is because you don't have a metric class for CTC in `deepcs.metrics`?

I was able to get things to work with the following hack:
1. Define `metrics` in the `main_ctc` script as follows:

```
    metrics = {
        "CTC": deepcs.metrics.GenericBatchMetric(lambda *params: baseloss(*wrap_ctc_args(*params)))
    }
```
2. Modify the `GenericBatchMetric.__call__` method as follows to handle `PackedSequence` instances 

```python
    def __call__(self, predictions, targets):
        """
        predictions: (B, *)
        targets : (B, *)
        """
        # We suppose is batch averaged
        if isinstance(targets, torch.nn.utils.rnn.PackedSequence):
            B = targets.unsorted_indices.shape[0]
        else:
            B = targets.shape[0]
        self.cum_metric += B * self.metric(predictions, targets).item()
        self.num_samples += B
```

Hope that's helpful!

The full traceback I got was:
```
$ python main_ctc.py train --debug
INFO:__main__:Training
INFO:__main__:Normalization coefficients : -31, 32
Building a train loader with batch size = 128
The dataset contains 128 samples
INFO:__main__:## Summary of the model architecture
=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
CTCModel                                 --
├─Sequential: 1-1                        --
│    └─Conv2d: 2-1                       14,464
│    └─BatchNorm2d: 2-2                  64
│    └─Hardtanh: 2-3                     --
│    └─Dropout2d: 2-4                    --
│    └─Conv2d: 2-5                       236,576
│    └─BatchNorm2d: 2-6                  64
│    └─Hardtanh: 2-7                     --
│    └─Dropout2d: 2-8                    --
├─GRU: 1-2                               70,828,032
├─Sequential: 1-3                        --
│    └─Linear: 2-9                       90,156
=================================================================
Total params: 71,169,356
Trainable params: 71,169,356
Non-trainable params: 0
=================================================================


## Executed command :
main_ctc.py train --debug

## Args : 
 Namespace(command='train', batch_size=128, debug=True, num_epochs=50, base_lr=0.0005, grad_clip=None, datasetroot='/home/marty/Documents/data/vocal/cv-corpus-11.0-2022-09-21', nthreads=6, min_duration=1, max_duration=5, nmels=80, nlayers_rnn=4, nhidden_rnn=1024, cell_type='GRU', train_augment=False, weight_decay=0.01, dropout=0.1, modelpath=None, audiofile=None, beamwidth=10, beamsearch=False, baselogdir=PosixPath('logs'), logname=None)
INFO:__main__:>>>>> Results saved in logs/ctc_1
Traceback (most recent call last):
  File "/home/marty/Documents/repos/vocalpy/deeplearning-lectures/LabsSolutions/02-pytorch-asr/main_ctc.py", line 443, in <module>
    eval(f"{args.command}(args)")
  File "<string>", line 1, in <module>
  File "/home/marty/Documents/repos/vocalpy/deeplearning-lectures/LabsSolutions/02-pytorch-asr/main_ctc.py", line 166, in train
    ftrain(
  File "/home/marty/miniconda3/envs/dl-lecture-env/lib/python3.10/site-packages/deepcs/training.py", line 60, in train
    bm.reset()
AttributeError: 'function' object has no attribute 'reset'
```

**Comment by jeremyfix** [comment]
Thank you very much for your catch and the detailed investigation.

Actually, you are right, I'm using these codes for teaching but the development pipeline is not yet that robust; I actually have in mind to somehow bring in CI to run tests on the code base , hopefully catching that sort of issues earlier ;

For the issue you mention, I indeed refactored the computation of the metrics to allow accumulation while iterating over batches. I unfortunately did not yet test the lab of ASR.  I will check your suggestion and fix this soon .

**Comment by NickleDave** [comment]
:+1: understood! Closing for now, just wanted to let you know. Thank you again for sharing the code, I find the `pad` -> `packed` API really confusing and I think I might not be the only one. It's very helpful to see a real-world example
